package com.cms.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWxAd<M extends BaseWxAd<M>> extends Model<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setMasterId(java.lang.Long masterId) {
		set("master_id", masterId);
		return (M)this;
	}
	
	public java.lang.Long getMasterId() {
		return getLong("master_id");
	}

	public M setAgencyId(java.lang.Long agencyId) {
		set("agency_id", agencyId);
		return (M)this;
	}
	
	public java.lang.Long getAgencyId() {
		return getLong("agency_id");
	}

	public M setIndustryId(java.lang.Long industryId) {
		set("industry_id", industryId);
		return (M)this;
	}
	
	public java.lang.Long getIndustryId() {
		return getLong("industry_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setMoney(java.lang.String money) {
		set("money", money);
		return (M)this;
	}
	
	public java.lang.String getMoney() {
		return getStr("money");
	}

	public M setStartTime(java.util.Date startTime) {
		set("start_time", startTime);
		return (M)this;
	}
	
	public java.util.Date getStartTime() {
		return get("start_time");
	}

	public M setDays(java.lang.Integer days) {
		set("days", days);
		return (M)this;
	}
	
	public java.lang.Integer getDays() {
		return getInt("days");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateTime(java.lang.Integer createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.lang.Integer getCreateTime() {
		return getInt("create_time");
	}

}
