package com.cms.entity;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("mzlt_ad", "id", Ad.class);
		arp.addMapping("mzlt_ad_industry", "id", AdIndustry.class);
		arp.addMapping("mzlt_ad_master", "id", AdMaster.class);
		arp.addMapping("mzlt_ad_position", "id", AdPosition.class);
		arp.addMapping("mzlt_admin", "id", Admin.class);
		// Composite Primary Key order: adminId,roleId
		arp.addMapping("mzlt_admin_role", "adminId,roleId", AdminRole.class);
		arp.addMapping("mzlt_agency", "id", Agency.class);
		arp.addMapping("mzlt_area", "id", Area.class);
		arp.addMapping("mzlt_article", "id", Article.class);
		arp.addMapping("mzlt_article_category", "id", ArticleCategory.class);
		arp.addMapping("mzlt_friend_link", "id", FriendLink.class);
		arp.addMapping("mzlt_receiver", "id", Receiver.class);
		arp.addMapping("mzlt_role", "id", Role.class);
		arp.addMapping("mzlt_wx_ad", "id", WxAd.class);
	}
}

