package com.cms.entity;

import java.util.List;

import org.apache.commons.lang.StringUtils;

import com.cms.entity.base.BaseAdIndustry;
import com.cms.util.DBUtils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdIndustry extends BaseAdIndustry<AdIndustry> {
	public static final AdIndustry dao = new AdIndustry().dao();

   /**
     * 查找广告主分页
     * 
     * @param pageable
     *            分页信息
     * @return 广告主分页
     */
    public Page<AdIndustry> findPage(String name,Integer pageNumber,Integer pageSize){
        String filterSql = "";
        if(StringUtils.isNotBlank(name)){
            filterSql+= " and name like '%"+name+"%'";
        }
        String orderBySql = DBUtils.getOrderBySql("createDate desc");
        return paginate(pageNumber, pageSize, "select *", "from mzlt_ad_industry where 1=1 "+filterSql+orderBySql);
    }
    
    /**
     * 查找广告主分页
     * 
     * @param pageable
     *            分页信息
     * @return 广告主分页
     */
    public List<AdIndustry> findList(){
        return find("select * from mzlt_ad_industry order by name desc");
    }
}
