package com.cms.entity;

import java.util.List;

import org.apache.commons.lang.StringUtils;

import com.cms.entity.base.BaseAdMaster;
import com.cms.util.DBUtils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdMaster extends BaseAdMaster<AdMaster> {
	public static final AdMaster dao = new AdMaster().dao();

    /**
     * 地区
     */
    private Area area;
    
    /**
     * 行业
     */
    private AdIndustry adIndustry;
    

   /**
     * 查找广告主分页
     * 
     * @param pageable
     *            分页信息
     * @return 广告主分页
     */
    public Page<AdMaster> findPage(String mobile,Integer pageNumber,Integer pageSize){
        String filterSql = "";
        if(StringUtils.isNotBlank(mobile)){
            filterSql+= " and mobile like '%"+mobile+"%'";
        }
        String orderBySql = DBUtils.getOrderBySql("createDate desc");
        return paginate(pageNumber, pageSize, "select *", "from mzlt_ad_master where 1=1 "+filterSql+orderBySql);
    }
    
    /**
     * 根据用户名查找广告主
     * 
     * @param username
     *          用户名
     * @return  广告主
     */
    public AdMaster findByUsername(String username){
        return findFirst("select * from mzlt_ad_master where username=? ", username);
    }
    
    /**
     * 根据电话查找广告主
     * 
     * @param username
     *          用户名
     * @return  广告主
     */
    public AdMaster findByMobile(String mobile){
        return findFirst("select * from mzlt_ad_master where mobile=? ", mobile);
    }
    
    /**
     * 获取地区
     * 
     * @return 地区
     */
    public Area getArea(){
        if(area == null){
            area = new Area().dao().findById(getAreaId());
        }
        return area;
    }
    
    /**
     * 获取行业
     * 
     * @return 行业
     */
    public AdIndustry getAdIndustry(){
        if(adIndustry == null){
        	adIndustry = new AdIndustry().dao().findById(getIndustryId());
        }
        return adIndustry;
    }
    
    public List<AdMaster> findList() {
    	return find("select * from mzlt_ad_master order by username desc");
    }
    
}
