package com.cms.entity;

import java.util.List;

import org.apache.commons.lang.StringUtils;

import com.cms.entity.base.BaseAgency;
import com.cms.util.DBUtils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agency extends BaseAgency<Agency> {
	public static final Agency dao = new Agency().dao();

    /**
     * 地区
     */
    private Area area;
    
    /**
     * 会员session名称
     */
    public static final String SESSION_AGENCY="session_agency";
    
   /**
     * 查找会员分页
     * 
     * @param pageable
     *            分页信息
     * @return 会员分页
     */
    public Page<Agency> findPage(String mobile,Integer pageNumber,Integer pageSize){
        String filterSql = "";
        if(StringUtils.isNotBlank(mobile)){
            filterSql+= " and mobile like '%"+mobile+"%'";
        }
        String orderBySql = DBUtils.getOrderBySql("createDate desc");
        return paginate(pageNumber, pageSize, "select *", "from mzlt_agency where 1=1 "+filterSql+orderBySql);
    }
    
    /**
     * 根据用户名查找会员
     * 
     * @param username
     *          用户名
     * @return  会员
     */
    public Agency findByUsername(String username){
        return findFirst("select * from mzlt_agency where username=? ", username);
    }
    
    /**
     * 根据电话查找会员
     * 
     * @param username
     *          用户名
     * @return  会员
     */
    public Agency findByMobile(String mobile){
        return findFirst("select * from mzlt_agency where mobile=? ", mobile);
    }
    
    /**
     * 获取地区
     * 
     * @return 地区
     */
    public Area getArea(){
        if(area == null){
            area = new Area().dao().findById(getAreaId());
        }
        return area;
    }
    
    public List<Agency> findList() {
    	return find("select * from mzlt_agency by username desc");
    }
}
