package com.cms.entity;

import org.apache.commons.lang.StringUtils;

import com.cms.entity.base.BaseWxAd;
import com.cms.util.DBUtils;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxAd extends BaseWxAd<WxAd> {
	public static final WxAd dao = new WxAd().dao();
	
   /**
     * 微信广告查询页面
     * 
     * @param pageable
     *            分页信息
     * @return 微信广告主分页
     */
    public Page<WxAd> findPage(String adName, String industryId, String masterId, String agencyId,
    		String mobile, Integer pageNumber, Integer pageSize){
    	String seleteSql = "SELECT"
    				+ " a.*,"
    				+ " m.id AS masterId,"
    				+ " m.username AS masterName,"
    				+ " m.mobile,"
    				+ " i.id AS industryId,"
    				+ " i.name AS industryName";
    	String fromSql = "FROM"
    			+ " mzlt_wx_ad a"
    			+ " LEFT JOIN mzlt_ad_master m"
    			+ " ON a.master_id = m.id"
    			+ " LEFT JOIN mzlt_ad_industry i"
    			+ " ON a.industry_id = i.id where 1=1 ";
        if(StringUtils.isNotBlank(adName)){
        	fromSql+= " and a.ad_name like '%"+adName+"%'";
        }
        if(StringUtils.isNotBlank(industryId)){
        	fromSql+= " and a.industry_id = '"+industryId+"'";
        }
        if(StringUtils.isNotBlank(masterId)){
        	fromSql+= " and a.master_id = '"+masterId+"'";
        }
        if(StringUtils.isNotBlank(agencyId)){
        	fromSql+= " and a.agency_id = '"+agencyId+"'";
        }
        if(StringUtils.isNotBlank(mobile)){
        	fromSql+= " and m.mobile like '"+mobile+"%'";
        }
        String orderBySql = DBUtils.getOrderBySql("createDate desc");
        return paginate(pageNumber, pageSize, seleteSql, fromSql + orderBySql);
    }
}
